name: Convert and Deploy Jupyter Notebook

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Convert Notebook to HTML
      run: |
        jupyter nbconvert --to html 'Financial News Strategy/2. Sentence Embeddings.ipynb'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # The directory containing the HTML file
        publish_branch: gh-pages  # The branch to deploy to (usually gh-pages)
