name: Execute and Convert Notebook to HTML

on:
  push:
    branches:
      - financial-news-strategy

jobs:
  execute-and-convert:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute and convert notebook to HTML
      run: |
        jupyter nbconvert --to html --execute 'Financial News Strategy/2. Sentence Embeddings.ipynb'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAT }}  # Use the personal access token
        publish_dir: ./  # The directory containing the HTML file
        publish_branch: gh-pages  # The branch to deploy to (usually gh-pages)
